name: pull-request-workflow
on:
  pull_request:
    types: [opened] # Pull Request가 생성된 시점에만 GitHub Actions 실행

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo hello world
      - name: step2
        run: |
          echo hello world
          echo github action
